### ISSUE TITLE
java not found

### ISSUE THREAD

**Issue by Edwardthedog2** [jkutner/heroku-buildpack-minecraft#14]
So, when I deploy the Heroku app, ngrok starts fine, but the Minecraft server doesn't start. When I ran heroku logs, I noticed that when the server tried to start, the app returned that the java command was not found. It's worked for me in the past, but now it seems like java doesn't install for some reason.

**Comment by jkutner** [comment]
Make sure you have the `heroku/jvm` buildpack too. It's required on the new heroku-16 stack, which does not include Java.

**Comment by Edwardthedog2** [comment]
Ohh okay. I guess I didn't know it required that now. Sorry.

Thank you.
