### ISSUE TITLE
Alternative to s3?

### ISSUE THREAD

**Issue by gamer4life1** [jkutner/heroku-buildpack-minecraft#22]
Does this buildpack work without s3 or with another service?

**Comment by jkutner** [comment]
It works without s3, but you'll lose your data every 24 hours. It isn't setup to work with another kind of service, but it could be. I'd accept a PR.

**Comment by gamer4life1** [comment]
Would it work with the Dropbox API?

**Comment by jkutner** [comment]
possibly

**Comment by gamer4life1** [comment]
I will work on a PR on that subject.

**Comment by gamer4life1** [comment]
This should be closed. For anybody else, please check out my [repo](https://github.com/gamer4life1/minecraftBuildpack)...
