### ISSUE TITLE
No Minecraft Screen

### ISSUE THREAD

**Issue by TheTrumpeter** [jkutner/heroku-buildpack-minecraft#24]
I followed your instructions meticulously, and I cannot connect to the Minecraft Server console using 'screen -r minecraft'. I get the response "There is no screen to be resumed matching Minecraft.
Then I try just 'screen -r' and I get the response "There is no screen to be resumed."

Also, I cannot connect to the Minecraft server from within the client. It just says "failed to connect to server: Disconnected".

Please help!

**Comment by gamer4life1** [comment]
Could you attach your logs? It might be because of a script failure...

**Comment by dartrix** [comment]
same issue here 
some logs
[arcane-taiga-79782-logs-1555861074953.txt](https://github.com/jkutner/heroku-buildpack-minecraft/files/3101385/arcane-taiga-79782-logs-1555861074953.txt)

**Comment by dartrix** [comment]
i fixed it by deleting the eula and letting the server create a new one and then changing 

> eula=false

 to 

> eula=true

**Comment by gamer4life1** [comment]
This should be closed. Did you solve your issue?

**Comment by TheTrumpeter** [comment]
Yes, I went with Realms instead. Please close.

**Comment by gamer4life1** [comment]
@jkutner  Please close!
