### ISSUE TITLE
Github problem

### ISSUE THREAD

**Issue by Brocho1337** [jkutner/heroku-buildpack-minecraft#36]
I only have the eula.txt and server.properties file.

```
-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed
```

**Comment by brazzmo** [comment]
I get the same thing, but I'm afraid that jkutner is either no longer updating this, or he no longer has access to his Github account, either way, you probably won't find results here.
