### ISSUE TITLE
ngrok download URL is no longer correct

### ISSUE THREAD

**Issue by saanvik** [jkutner/heroku-buildpack-minecraft#4]
dl.ngrok.com is no longer the correct URL for downloading, so the build on Heroku fails.

I created a pull request to fix this at https://github.com/jkutner/heroku-buildpack-minecraft/pull/3

Replacing the buildpack URL with my forked repo (https://github.com/saanvik/heroku-buildpack-minecraft) allows the app to build and run.

**Comment by gamer4life1** [comment]
@jkutner This issue should be closed...
