### ISSUE TITLE
Problem with pushing to heroku master: App not compatible with buildpack

### ISSUE THREAD

**Issue by Lukaja21** [jkutner/heroku-buildpack-minecraft#41]
Counting objects: 3, done.
Writing objects: 100% (3/3), 225 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to floating-basin-28083.
remote:
To https://git.heroku.com/floating-basin-28083.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/floating-basin-28083.git'

**Comment by CraigRobertWhite** [comment]
I get this as well.

**Comment by TelmoMS** [comment]
Try creating a requirements.txt in the master branch with s3cmd
