### ISSUE TITLE
Invalid jar file error for version 1.15.2

### ISSUE THREAD

**Issue by SubhrajitPrusty** [jkutner/heroku-buildpack-minecraft#52]
`Error: Invalid or corrupt jarfile minecraft.jar`

I also noticed that when no version is specified 1.14.4 is being installed even when 1.15.2 is [set as default](https://github.com/jkutner/heroku-buildpack-minecraft/blob/118831a16d5442ce18e6a595d67dc6ab3abd81f2/bin/compile#L63)

**Comment by SubhrajitPrusty** [comment]
I noticed the [buildpack](https://buildpack-registry.s3.amazonaws.com/buildpacks/jkutner/minecraft.tgz) has not been updated with the new code.

**Comment by jkutner** [comment]
thanks, it's updated now
