### ISSUE TITLE
What is the expected pricing?

### ISSUE THREAD

**Issue by WixoLeo** [jkutner/heroku-buildpack-minecraft#64]
What is the average pricing each month? Lets say for 5-10 people playing everyday?

**Comment by jkutner** [comment]
You can try with a free dyno, but it will likely struggle and run out of memory. I use a [Standard 2X dyno](https://www.heroku.com/pricing), which is $50/month if you run it 24/7. But I only run it when I'm playing so it's much much cheaper. The dynos are pro-rated to the second.

**Comment by WixoLeo** [comment]
> You can try with a free dyno, but it will likely struggle and run out of memory. I use a [Standard 2X dyno](https://www.heroku.com/pricing), which is $50/month if you run it 24/7. But I only run it when I'm playing so it's much much cheaper. The dynos are pro-rated to the second.

Interesting, thank you! Well done on the project!
