### ISSUE TITLE
Can not connect to server from Minecraft Java Edition

### ISSUE THREAD

**Issue by josuablejeru** [jkutner/heroku-buildpack-minecraft#65]
After following the instructions provided by the README I was not able to connect to the server from Minecraft because of a Timeout. 

If I try the url`0.tcp.ngrok.io:16299` I can't connect at all. If I'm using `ngrok.io:16299` Minecraft tries to connect but returns a Timeout error.

Thanks for your support and help.

**Comment by jkutner** [comment]
Check the `heroku logs` to see if the Minecraft server started up successfully. Then also check the ngrok.com dashboard to see if the tunnel is active.
