### ISSUE TITLE
[Non-Issue] How Does It Work?

### ISSUE THREAD

**Issue by TheBotlyNoob** [jkutner/heroku-buildpack-minecraft#70]
What do the trap commands do, why do you have eval commands everywhere, and why does this buildpack activate the screen, but [this one](https://github.com/TheBotlyNoob/heroku-buildpack-AmongUsServer/) does not?

**Comment by SuperHarmony910** [comment]
wtf

**Comment by TheBotlyNoob** [comment]
idk
